build_sl_vitis2019-2_x11:
    extends: .job_template
    variables:
        OS: sl
        OS_VERSION: "7"
        SERIES: "vitis"
        VERSION: "2019.2"
        VIEW: x11

build_sl_vitis2019-2_x11_dockerhub:
    extends: .job_template
    variables:
        CI_REGISTRY: https://index.docker.io/v1/
        CI_REGISTRY_USER: ${DOCKER_USERNAME}
        CI_REGISTRY_PASSWORD: ${DOCKER_PASSWORD}
        CI_REGISTRY_IMAGE:  index.docker.io/aperloff
        OS: sl
        OS_VERSION: "7"
        SERIES: "vitis"
        TO: "${CI_REGISTRY_IMAGE}/vivado-docker:${OS}${OS_VERSION}_${SERIES}${VERSION}_${VIEW}"
        VERSION: "2019.2"
        VIEW: x11